### ISSUE TITLE
[FEAT] 비교하기 목록 조회 API

### ISSUE THREAD

**Issue by junggyo1020** [NOW-SOPT-APP1-YeogiEottae/YeogiEottae-Server#13]
# ⚙️ ISSUE
- 비교하기 목록을 조회하는 API 구현

# 📄 To-Do

- [x] 도메인 모델(Entity) 정의
- [x] DTO(Record) 정의
- [x] Repository 인터페이스 생성
- [x] Service 클래스 작성
- [x] Controller 클래스 작성
- [x] 예외 처리
- [x] Swagger 테스트
