### ISSUE TITLE
[Fix] 비교하기 목록 삭제하기 API, 일부 오류 수정

### ISSUE THREAD

**Issue by junggyo1020** [NOW-SOPT-APP1-YeogiEottae/YeogiEottae-Server#33]
# ⚙️ ISSUE
- 객실만 찜목록에 추가하면, 호텔정보가 반환되지 않았던 오류를 해결하도록 구현하기
- 비교하기 목록을 삭제하는 API 구현

# 📄 To-Do

- [x] 도메인 모델(Entity) 정의
- [x] DTO(Record) 정의
- [x] Repository 인터페이스 생성
- [x] Service 클래스 작성
- [x] Controller 클래스 작성
- [x] 예외 처리
- [x] Swagger 테스트
